# Generated by Django 4.0.2 on 2022-02-28 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmodel',
            name='book_price',
            field=models.IntegerField(default=250),
        ),
    ]
